# This is where our jsps are
spring.mvc.view.prefix=/WEB-INF/jsps/
spring.mvc.view.suffix=.jsp
server.port=${PORT:8080}


# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# Datasource

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Display sql in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# create tables at startup

spring.jpa.hibernate.ddl-auto=update
# create, update, create-drop